### PR TITLE
Add logic to warn about docker network claiming

### PR DESCRIPTION
**Pull request by 0x6d6f7468**
Added new function `warn_network_in_use`. Takes in subnets and checks if they are present in the routing table and also not present in existing docker networks.

Relevant to activecm/AI-Hunter#579

### CODE REVIEW

**Comment by 0x6d6f7468** [comment]
Technically WIP, because the URL in the message needs updating when content is added to the FAQ on this topic.

**Comment by 0x6d6f7468** [comment]
No longer WIP. Thanks, @mrkeithchew!

This is the output of the function:

image

**Comment by Zalgo2462** [comment]
Testing this, I noticed a problem. If the user edits /etc/docker/daemon.json so the networks assigned to the containers changes, the installer is unaware of the change and repeats this warning. This is because the networks (as called in AC-Hunter) are statically defined in the installer. Unfortunately, figuring out which networks will be claimed from /etc/docker/daemon.json is rather difficult with bash. 

For the time being, we could only call this function if /etc/docker/daemon.json doesn't exists. It would be a quick fix that would solve a majority of the cases. 

To properly solve this, I think we'd need to read the JSON from /etc/docker/daemon.json, extract the network pools its set to use and then check if the network pools collide with anything in the route table. Unfortunately, we wouldn't be able to do substring checks, we'd need to do full `ipcalc` type operations. 

We might consider defining a network to use in the AC-Hunter Docker compose files so that way we know what network will be used ahead of time. If we go down that route, we'll want to change the FAQ entry to direct users towards editing the compose file instead. I think I prefer this route.

@ethack What are your thoughts?

**Comment by ethack** [comment]
I think the best effort solution is to disable the warning if we detect that there's already a custom subnet defined. No need to check further as that already is an uncommon case and signals an advanced user.

I talked this over with @Zalgo2462 already and he agrees.

So something like this (I did not run this to check):
```bash
if [ -f /etc/docker/daemon.json ] && grep -q default-address-pools /etc/docker/daemon.json; then
  # disable the warning even if we've detected a collision
fi
```

**Pull request merged**
